config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tweeets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "tweeets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweeets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

	private

	def sign_up_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

	def acount_update_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tweeets
  # GET /tweeets.json
  def index
    @tweeets = Tweeet.all.order("created_at DESC")
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1
  # GET /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = current_user.tweeets.build
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets
  # POST /tweeets.json
  def create
    @tweeet = current_user.tweeets.build(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to root_path, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1
  # PATCH/PUT /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1
  # DELETE /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
</head>

  <body>
  <% if flash[:notice]%>
      <div class="notification is-primary global-notification ">
      <p class="notice has-text-white"><%= notice %></p>
      </div> 
  <% end %>

  <% if flash[:alert]%>
      <div class="notification is-danger global-notification ">
      <p class="alert"><%= alert %></p>
      </div> 
<% end %>

  <nav class="navbar is-info">
    <div class="navbar-brand">
      <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-4 has-text-white"> Twitter</h1>
      <% end %> 

      <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id = "navbarExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="field is-grouped level">
          <p class="control">
            <%= link_to "New tweet", new_tweeet_path, class:"button is-info is-inverted"%>
          </p>
          <% if user_signed_in? %>
          <p class="control">
          <%= link_to current_user.name, edit_user_registration_path, class: "button is-info"%>
          </p>
           <p class="control">
          <%= link_to "logout", destroy_user_session_path, method: :delete, class: "button is-info"%>
          </p>
          <% end %>
        </div>
      </div>
    </div>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/tweeets/_feed.html.erb
<div class="column is-half">
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/64x64.png">
      </p>
    </figure>
<div class="media-content">
    <%= render 'tweeets/form' %>
</div>
</article>


<% @tweeets.each do | tweeet | %>
 <div class="box">
 <article class="media">
 <div class="media-left">
 <figure class="image is-64x64">
 <img src="https://bulma.io/images/placeholders/64x64.png">
 </figure>
 </div>
 <div class="media-content">
    <div class="content">
    <strong>Rumbie Mudzie</strong><br />
    <small>@webcrunch</small><br/>
    <p><%= tweeet.tweeet %></p>
    </div>
    <nav class="level">
    <div class="level-left is-mobile">
    <%= link_to tweeet, class: "level-item" do %>
    <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
    <% end %>
    <%= link_to edit_tweeet_path(tweeet), class: "level-item" do%>
    <span class="icon"><i class="fa fa-pencil" arial-hidden="true"></i></span>
    <% end %>
    <%= link_to tweeet, method: :delete, data: {confirm: "Are you sure you want to delete this tweet?"} do %>
    <span class="icon"><i class="fa fa-trash-o" arial-hidden="true"></i></span>
    <% end %>
    </div>
    </nav>
 </div>
 </article>
 </div>
 <% end %>
 </div>

app/views/tweeets/_form.html.erb
<%= simple_form_for(@tweeet) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :tweeet, label: "Tweeet your tweeets", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/tweeets/_trends.html.erb
<div class="column is-one-quarter">
<nav class="panel">
<p class="panel-heading">What is Trending?</p>
<a class="panel-block">
Trend 1
</a>
<a class="panel-block">
Trend 2
</a>
<a class="panel-block">
Trend 3
</a>
<a class="panel-block">
Trend 4
</a>
<a class="panel-block">
Trend 5
</a>
<a class="panel-block">
Trend 6
</a>
</nav>
</div>

app/views/tweeets/_who-to-follow.html.erb
<div class="column"> 
    <nav class="panel">
    <p class="panel-heading">Who to Follow</p>
    </nav>
    <div class="panel-block">
    <article class="media">
    <div class="media-left">
    <figure class="image is-32x32">
    <img src="https://bulma.io/images/placeholders/64x64.png">
    </figure>
    </div>
    <div class="media-content">
    <div class="content">
    <p>
    <strong>Deffy Dee</strong>
    <small>@deffydee</small>
     <div class="button is-info has-text-white">Follow</div>
    </p>
    </div>
    </div>
    </article>
    </div>

    <div class="panel-block">
    <article class="media">
    <div class="media-left">
    <figure class="image is-32x32">
    <img src="https://bulma.io/images/placeholders/64x64.png">
    </figure>
    </div>
    <div class="media-content">
    <div class="content">
    <p>
    <strong>Deffy Dee</strong>
    <small>@deffydee</small>
     <div class="button is-info has-text-white">Follow</div>
    </p>
    </div>
    </div>
    </article>
    </div>

 <div class="panel-block">
    <article class="media">
    <div class="media-left">
    <figure class="image is-32x32">
    <img src="https://bulma.io/images/placeholders/64x64.png">
    </figure>
    </div>
    <div class="media-content">
    <div class="content">
    <p>
    <strong>Deffy Dee</strong>
    <small>@deffydee</small>
     <div class="button is-info has-text-white">Follow</div>
    </p>
    </div>
    </div>
    </article>
    </div>

</div>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
  <section class="section">
  <div class="container">
  <div class="columns">
  <%= render 'trends' %>
  <%= render 'feed' %>
  <%= render 'who-to-follow' %>
  </div>
  </div>
  </section>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>